name: spree_party
description: "AI-Powered Party Games Generator"
publish_to: 'none' 

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  webview_flutter: ^4.4.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"  
  adaptive_icon_background: "#000000"  
  adaptive_icon_foreground: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.jpg
